### ISSUE TITLE
[Spec][Idea]めざまし時計appの機能を洗い出す

### ISSUE THREAD

**Issue by akihisa-sumi** [akihisa-sumi/creator#1]
goal : めざましアプリのに組み込む機能を最低1つ以上決定する。（実現可能であること）

**Comment by akihisa-sumi** [comment]
[実現可能性◯]アラームを停める際に、3-4桁の計算が必要。

**Comment by akihisa-sumi** [comment]
[実現可能性◯]アラームを停める際に、自分の名前の発話が必要。

**Comment by akihisa-sumi** [comment]
[実現可能性△]アラームのメロディーを選択できる。
メロディー(自分の携帯中の音楽メディア+４人オリジナルメロディー+iphone既存メロディー)

**Comment by akihisa-sumi** [comment]
[実現可能性△]４人オリジナルメロディーはカスタマイズできる。(バイブ,音の高さ,音程)

**Comment by akihisa-sumi** [comment]
[実現可能性△]音量をiphone既存の音量以上のものにできる。

**Comment by akihisa-sumi** [comment]
[実現可能性△]はわからないという意味です。時間があれば調査をお願いいたします。

**Comment by taichiH** [comment]
[実現可能性○]毎回違う音（音楽とか、誰かの声とか）がランダムでなる。（違う音楽の方が起きやすいから）

**Comment by taichiH** [comment]
[実現可能性△]一定距離iPhoneが移動しないとアラームが止まらない。（位置センサーか、精度によってはGPS?）

**Comment by taichiH** [comment]
[実現可能性○]iPhone本体を使って何らかの動きをさせる。例えばiPhoneを10回振る（1ストローク30cm以上などと指定する）

**Comment by taichiH** [comment]
[実現可能性○]誰かの叫び声とかがアラーム音（音源は多分俺たちの声か誰かイケボの人に頼む、何種類もの意味不明な音源を用意する←簡単）（例えば説教するとか『今起きないと絶対後悔するぞ』とか）

**Comment by taichiH** [comment]
[実現可能性○]女の人の声（誰かに頼む）で彼女っぽい感じで、起きて！とか言ってもらえる（佐々木希のアイデアの佐々木希じゃなくて誰かの声バージョン）

**Comment by taichiH** [comment]
[実現可能性△]カメラ機能付きで、足を画像認識しないと止まらないアラーム（なんで足かというと、一番手から遠いい部位だから。→体が動く→起きる。）
別に足じゃなくても、なんらかの認識させたい物体を自分で写真撮って、それを認識しないと起きれないとか（その物体をベッドから遠いいところに置いておけば、嫌でもベッドから出なきゃダメ→起きる）

**Comment by ShusukeTatsumi** [comment]
[実現可能性○]モスキート音でみんな起きれるようになるはず！！(笑)

**Comment by ShusukeTatsumi** [comment]
[実現可能性○]アラーム音の周波数を調整できるアプリ。

対象者：大学生（若者）
1人暮らしでアラームを何回も切ってしまうダメ大学生が近隣住民に迷惑をかけずに済むようにする。(笑)

特徴：加齢により聞こえる周波数領域が減ってくることを利用して近隣の年配の方へのアラーム音被害を減らすことができる。

使用例：辰巳（23歳）なので、高い周波数（17000Hｚ）のアラーム音を設定する。23歳なので聞こえる。隣に住むマンションの大家さん（60代）は加齢のために、この周波数領域の音は聞こえない。その為、辰巳の鳴らすアラーム音を不快に感じなくてすむ。

参考までに
～10,000Hz…60歳以下

～12,000Hz…50歳以下

～15,000Hz…39歳以下

～16,000Hz…30歳以下

～17,000Hz…24歳以下

コメント：２度寝促進するから実用性は全くない。完全にネタアプリ。
だけど、面白いからネタでダウンロードしたくなるかも。
ダウンロードさえしてもらえればこちら（開発側）としては利益になる。(笑)
アプリ開発に必ずしも実用性を求める必要はない。(笑)

**Comment by akihisa-sumi** [comment]
天気表示機能
服装表示機能
多言語対応機能(3言語)
目覚まし機能
