### ISSUE TITLE
[Spec][Idea]計算機appの機能を洗い出す

### ISSUE THREAD

**Issue by akihisa-sumi** [akihisa-sumi/creator#2]
goal : 計算機アプリのに組み込む機能を最低1つ以上決定する。（実現可能であること）

**Comment by akihisa-sumi** [comment]
[実現可能性○]4則計算(和差乗除)ができる。

**Comment by akihisa-sumi** [comment]
[実現可能性△]有効桁50桁以上の計算ができる。

**Comment by akihisa-sumi** [comment]
[実現可能性△]4次元方程式まで解くことができる。

**Comment by akihisa-sumi** [comment]
[実現可能性△]写真の文字を認識して計算することができる。

**Comment by akihisa-sumi** [comment]
[実現可能性△]はわからないという意味です。時間があれば調査をお願いいたします。

**Comment by taichiH** [comment]
[実現可能性○]行列計算をできる（逆行列、固有値、固有ベクトル、ノルム、など）　
ポイント（デザインを工夫する）

**Comment by taichiH** [comment]
[実現可能性△]スーパーとかで、値札についてる値段にカメラを向けたら、値段を認識してくれて、商品が増えるたびに、カメラを向けるだけで、自動で足し算してくれる。（あれ、今いくらかな？ってなった時に、すぐわかる）

**Comment by taichiH** [comment]
[実現可能性△△]置かれてるお金をカメラで写真撮ると、自動で、いくらあるかわかる（画像認識する対象がはっきりしてるから、意外と認識できるんじゃないかっていう考え）

**Comment by ShusukeTatsumi** [comment]
[実現可能性○]変換機能（Ex.　年齢早見、n進数⇔10進数、通貨、消費税加算、西暦⇔和暦、割り勘幹事アプリ）

**Comment by ShusukeTatsumi** [comment]
[実現可能性○]家計簿アプリ。特に、「財布お口チャック家計簿」みたいなのにする。ユーザーが月間目標貯金額を事前に設定して置き、それを達成するように仕向けてくれるアプリ。支出が多くなると警告出すとか、エンタメが多いと「遊びすぎ！」って警告したりとか。
警告はメッセージで出すだけじゃなく、擬人化エージェントを用いると良いかも。

**Comment by ShusukeTatsumi** [comment]
[実現可能性○]そろばん　iPhoneのUIを発揮できる。アート面で攻める。実用性はありません。
俺そろばんの使い方わからんけど　(笑)

**Comment by ShusukeTatsumi** [comment]
↑方向性違うのでスルーしてもらってもかまいません。(笑)

**Comment by akihisa-sumi** [comment]
一般的な関数電卓の機能
+写真認識機能（時間があれば）
