### ISSUE TITLE
[居合斬り][implementation]saveScore()

### ISSUE THREAD

**Issue by akihisa-sumi** [akihisa-sumi/creator#31]

**Comment by shono1208** [comment]
//housing save data
var score:[String] = []
let defaults = NSUserDefaults.standardUserDefaults()
defaults.setObject(score, forKey:"SCORE")
defaults.synchronize()

//reading save data
var score: [String] = []
if(defaults.objectForKey("SCORE")){
    let objects = defaults.objectForKey("SCORE") as? NSArray
    var scoreString:AnyObject
    for scoreString in objects!{
        names.append(scoreString as NSString)
    }
}

**Comment by akihisa-sumi** [comment]
let userDefaults = UserDefaults.standard
saveScore() {
    userDefaults.set(1, forKey: "Key")
}
